export {default as Footer} from "./Footer/Footer"
export {default as Header} from "./Header/Header"
export {default as Modal} from "./Modal/Modal"
export {default as SettingComponent} from "./SettingComponent/SettingComponent"
export {default as SvgComponent} from "./SvgComponent/SvgComponent"
